project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - vignettes/*.qmd
    - prompts-listing.qmd
    - conversations-listing.qmd

website:
  title: "My AI Assistant"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: prompts-listing.qmd
        text: "Prompts"
      - href: conversations-listing.qmd
        text: "Conversations"
    right:
      - icon: github
        href: https://github.com/brad-cannell/my-ai-assistant
        aria-label: "GitHub repository"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-fold: true       # great for prompt/snippet repos
    code-tools: true


execute:
  eval: false
  echo: true
