---
title: "Projects"
output: rmarkdown::html_vignette
date: "2025-12-22"
updated: "2025-12-22"
vignette: >
  %\VignetteIndexEntry{Projects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Multiple AI companies have introduced "projects" to their browser-based AI assistants. 

OpenAI's documentation describes projects as, "smart workspaces that keep everything related to a long‑running effort in one place. Group together chats, upload reference files, and add custom instructions so ChatGPT remembers what matters and stays on‑topic. With memory, context, and flexible tools, they’re ideal for repeated and evolving work such as writing, research, planning, and more."

Anthropic's documentation describes projects as, "self-contained workspaces with their own chat histories and knowledge bases. Within each project, you can upload documents, provide context, and have focused chats with Claude."

Is there a way to get the benefits of "projects" when interacting with AI assistants using the API?


# Notes
- 2025-12-22: Left off here. I need to better understand how ellmer works before I can move on to recreating project functionality. 
- We will probably need to give each project a separate Rproj.





**Source:** 